-
  name: Backup sshd Config File
  hosts: localhost
  tasks:
    -
      name: If exists backup file - remove it
      file:
        path: /etc/ssh/sshd_config.backup
        state: absent

    -
      name: Backup sshd_config
      copy:
        src: /etc/ssh/sshd_config
        dest: /etc/ssh/sshd_config.backup
