-
  name: Restore old sshd backup
  hosts: localhost
  tasks:
    -
      name: If exists config file - remove it
      file:
        path: /etc/ssh/sshd_config
        state: absent

    
    - name: Restore old sshd config backup
      copy:
        src: /etc/ssh/sshd_config.backup
        dest: /etc/ssh/sshd_config
